language: python
python:
- 3.7-dev
os: linux
dist: xenial
sudo: true
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::6}
  - BUILD_TYPE="stellar-core"
  - TAG="v.9.2.0"
  - GIT_BRANCH=latest
  - secure: kR/yJ8XX/ky7G0uCQ22gL5fo2JUyK88cqxH99UVJU9e3DfVrx6rQLgWnYHxHT4ZAxpGySkPIHUc47i9wk9PHHnRhi+h9TnUKDMkU7mrycdCkFZ7xiUorBmU+hPJ9LLUn6ThbcR+JBUtGIWBS8wSGCjW7780tedKAz4AXobaueZL8s0C/eSCZbZ33uqWHj9GYpeeM4CilV6yjIye0+x5VV8rBmFUtrgiMZuJ1aJ7lEhkgr6VSKXNhiqLBAvF4GMnEEp48fGKOKeb/tHEcpNmzd0RKEua8oYTp46Rga7s9Zkzp72VnnT0NnbebJZVy9H/KlwiZ1u7o6543tKJtOc70H3YgsUI09vZIy2bYCkK/FzKZQbiWetZv/8vkhGLF1qrIxRs/7VvlnLxQ8R8o6dvGINewFVLjwD3aS8ScXYALKJf8ogBiP7dpx/kOaYTlFPjnyy5eDJMxLDrEC6DpO8s0u+OJKgPQClSapnEV7tcvx8NHM3xHu5ydvqZRA79mURtH03yCBDwn40GFwwqhwWIOgbqO2cdI6KVfNcrgiPjEUulqtDuG3dotWXXr6R9oK0E5Sx8KJK20bhSsQbARQGqPl4g26bbVKVU5xpdsuJSjj8K3JmGWRmxMatQKpjV7rXNq2khJamLr6cdX0xNq9jL5WYUT7AXMbSrEcYXX8Rh9AIs=
  - secure: EAIQUsyz4C1DiCUycJnzYUio4wyg0eLslqwBCh4yXf9fo4er5c0JalUxeSxGzIf+xdLWKaFMA/BSd9VFEovfhutI/plyXirP10EmWUzev2SNLzc03x7oRikCrVPPlKo93wGWdt/mL/Xmzpw9kSRWXSZXamm1Hu0mh32KY0aTML+1cfGEXq0znLLF+i1vLtQmHvecTZ9cMtfHW1C2+SVi8bvmaRxP1KqtiSEG/lnSOnOs6VtYFnCBx9XrqFaxt1/2KMqPHmyEZTul9ThnHwz/SLpjCZbf7rGdS1HM2OspiOdvDAw2y2P+z6XCNxeFWcqMa2hOnGomltARDYku9hlssdoPVUK/dntOBFnJO4Mb2LTHg+N5I9L0gQi7ew7aj2UFz73n6yRqyJIS7FtYn5m52usReUFr/z/RSCihXdSPG8DBjLff8Tb/YLW7yqd25tjtf04ASLfi111k5OZw3aGc/W/NiUlm+RIvTEz3HEj9X7UzYJpdbNsSGsEBdDevLpqZjDBKDbf8cdpQSmRFsQtrUhSddtJh0d6us5xYzlUeI01GFrRQWZwBpYO4U0HleoByDdymzWt+YJHDbnnYD63DTmd8IjeXdNGdNRyorIHxj1X1cn9OP6FKIDk8nQ4Adkhabi0jBxlqUbxA6EhS4AUWFlhDCCEn/3ErdVtTVHgnNQ0=
services:
- docker
addons:
  postgresql: '9.3'
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - automake
    - bison
    - clang-3.5
    - flex
    - g++-4.9
    - libpq-dev
    - libpq5
    - libstdc++6
    - libtool
    - pkg-config
    - clang-format-5.0
    - pandoc
    - libffi-dev
before_install:
- mkdir $COMMIT && cd $COMMIT
- git clone https://github.com/kinecosystem/blockchain-ops.git && cd blockchain-ops
- pip -V
- pipenv sync
- if [[ "$BUILD_TYPE" == "stellar-core" ]]; then pipenv run invoke build-core --branch="kinecosystem/master"
  --version=$GIT_BRANCH ; fi
install:
- docker login --username=$DOCKER_USER --password=$DOCKER_PASS
- export REPO=yonikashi/blocktest
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- echo $REPO:$TAG:$COMMIT
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
cache:
  directories:
  - "$HOME/.ccache"
  - ".libs"
notifications:
  email: false
  slack:
    secure: VYA87p8f6PgmOhL8b8DM4t6k8vPYjULpT7LBhvmNBNe8iiNDtTzLpRbUXg6t6Ij7Y3MU4uOJ5K617hCqs81VfRoOakbiYTWHeYSsMmIrUM4+d5MZM4pVP0/bCE49qt06bZINorh6IHChhfuvod3uyUqbgNrwRf/qDIIboFDIty8=
