language: cpp
dist: xenial1
sudo: true

compiler:
- clang
- gcc

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::6}
services:
  - docker
addons:
  postgresql: "9.3"
  apt:
    sources:
    - llvm-toolchain-trusty-3.5
    - llvm-toolchain-trusty-5.0
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - automake
    - bison
    - clang-3.5
    - flex
    - g++-4.9
    - libpq-dev
    - libpq5
    - libstdc++6
    - libtool
    - pkg-config
    - clang-format-5.0
    - pandoc
    - libffi-dev

before_install:
- mkdir $COMMIT && cd $COMMIT
- git clone https://github.com/yonikashi/blocktest.git && cd blocktest
- pip -V
- pip install --user invoke
- pip install --user pipenv
- pipenv sync
- pipenv run invoke build-core --latest
- docker tag images_stellar-core yonikashi/blocktest

script: ./travis-build.sh

cache:
  directories:
  - $HOME/.ccache
  - .libs

notifications:
  email: false
  slack:
    secure: VYA87p8f6PgmOhL8b8DM4t6k8vPYjULpT7LBhvmNBNe8iiNDtTzLpRbUXg6t6Ij7Y3MU4uOJ5K617hCqs81VfRoOakbiYTWHeYSsMmIrUM4+d5MZM4pVP0/bCE49qt06bZINorh6IHChhfuvod3uyUqbgNrwRf/qDIIboFDIty8=

